version: '3'
services:
  meteor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8888:3000
    volumes:
      - .:/app
      - ./docker:/docker_tools
    entrypoint: /docker_tools/meteor.sh
    tty: true
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: app_db
    volumes:
      - ./docker/mongo/.001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
